apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: {{.SpecialResource.Name}}
  name: {{.SpecialResource.Name}}
spec: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.SpecialResource.Name}}-buildah-helper
data:
  buildah-helper.sh: |-
    #!/bin/bash -x 

    CNT=
    MNT=

    FROM() { export CNT=$(buildah --storage-driver vfs from $1); }

    MOUNT() { export MNT=$(buildah --storage-driver vfs mount $CNT); }
    UMOUNT() { buildah --storage-driver vfs umount $CNT; }

    ENV() { buildah config --env $@; }
    RUN() { buildah --storage-driver vfs --isolation chroot run --user 0 $CNT -- $@; }
    RUNV() { buildah --storage-driver vfs --isolation chroot run --volume /etc/pki/entitlement-host:/etc/pki/entitlement:z --volume /tmp/overlay:/tmp/overlay:z --user 0 $CNT -- $@; }
    COPY() { buildah --storage-driver vfs copy $CNT $@; }
    COMMIT() { buildah --storage-driver vfs commit $CNT $1; }
    ENTRYPOINT() { buildah config --entrypoint $1 $CNT; }
    WORKINGDIR() { buildah --storage-driver vfs config --workingdir $1 $CNT; }
    PUSH() { buildah --storage-driver vfs push --tls-verify=false --authfile /root/.dockercfg  $@; }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.SpecialResource.Name}}-install-dependencies
data:
  install-depedencies.sh: |-
    #!/bin/bash
    
    UNAME=$(uname -r)

    # First update the base container to latest versions of everything
    yum update -y --enablerepo=rhel-8-for-x86_64-baseos-eus-rpms --releasever={{.OperatingSystemMajorMinor}}

    # Enable EUS and try to install kernel-devel and kernel-headers
    yum -y --enablerepo=rhel-8-for-x86_64-baseos-eus-rpms --releasever={{.OperatingSystemMajorMinor}} \
      --setopt=install_weak_deps=False --best install \
      kernel-devel-${UNAME} kernel-headers-${UNAME} kernel-core-${UNAME}
    
    # If EUS fails get kernel-devel and kernel-headers from machine-os-content
    if [ $? -eq 0 ]; then
      echo "EUS - kernel-devel-${UNAME} kernel-headers-${UNAME}  kernel-core-${UNAME} installed"
    else
      echo "EUS FAILED - installing from payload"
      KERNEL_DEVEL=$(find /tmp/overlay -name kernel-devel-${UNAME}.rpm -exec ls {} \; | tail)
      KERNEL_HEADERS=$(find /tmp/overlay -name kernel-headers-${UNAME}.rpm -exec ls {} \; | tail)
      KERNEL_CORE=$(find /tmp/overlay -name kernel-core-${UNAME}.rpm -exec ls {} \; | tail)
       
      echo "KERNEL DEVEL: $KERNEL_DEVEL"
      echo "KERNEL HEADERS: $KERNEL_HEADERS"
      echo "KERNEL CORE: $KERNEL_CORE"

      yum -y --setopt=install_weak_deps=False --best install $KERNEL_DEVEL
      yum -y --setopt=install_weak_deps=False --best install $KERNEL_HEADERS
      yum -y --setopt=install_weak_deps=False --best install $KERNEL_CORE
    fi

    # Additional packages that are mandatory for driver-containers
    yum -y --setopt=install_weak_deps=False --best install elfutils-libelf-devel kmod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.SpecialResource.Name}}-entrypoint
data:
  entrypoint.sh: |-
    #!/bin/bash -x 
    set -e
    cd /tmp

    yum -y install buildah git make --setopt=install_weak_deps=False

    git clone {{.SpecialResource.Spec.DriverContainer.Source.Git.Uri}}

    source /bin/buildah-helper.sh

    UNAME=$(uname -r)
    SCRIPT_NAME=install-depedencies.sh
    TAG={{.SpecialResource.Namespace}}/{{.SpecialResource.Name}}:v${UNAME}

    # --------- Container instructions START ----------------------------------
 
    FROM registry.access.redhat.com/ubi8/ubi

    WORKINGDIR /tmp
 
    COPY /bin/${SCRIPT_NAME} .
    RUNV bash -c $(pwd)/${SCRIPT_NAME}
 
    # Install directly into the chroot, this way we do not have to install
    # additinoal packages like git into the container to install from a git repo
    # The deps are resolved by the outer image. 
    MOUNT
    cd kmods-via-containers
    make install DESTDIR=${MNT}/usr/local CONFDIR=${MNT}/etc/
    UMOUNT

    COMMIT ${TAG}
    PUSH   ${TAG} image-registry.openshift-image-registry.svc:5000/${TAG}

    # --------- Container instructions END ------------------------------------

    sleep infinity 
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{.SpecialResource.Name}}
  name: {{.SpecialResource.Name}}
spec:
  serviceAccount: builder
  serviceAccountName: builder
  restartPolicy: OnFailure
  containers:
  - name: {{.SpecialResource.Name}}-ctr
    image: "registry.access.redhat.com/ubi8:latest"
    command: ["/bin/entrypoint.sh"]
    volumeMounts:
        - name: entrypoint
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
        - name: install-depedencies
          mountPath: /bin/install-depedencies.sh
          readOnly: true
          subPath: install-depedencies.sh
        - name: buildah-helper
          mountPath: /bin/buildah-helper.sh
          readOnly: true
          subPath: buildah-helper.sh
        - name: overlay
          mountPath: /tmp/overlay
          readOnly: true
        - name: dockercfg
          mountPath: /root
          readOnly: true
  volumes:
    - name: dockercfg
      secret:
        secretName: {{.PushSecretName}}
    - name: overlay
      hostPath:
      path: /var/lib/containers/storage/overlay
    - name: entrypoint
      configMap:
        defaultMode: 0700
        name: {{.SpecialResource.Name}}-entrypoint
    - name: install-depedencies
      configMap:
        defaultMode: 0700
        name: {{.SpecialResource.Name}}-install-dependencies
    - name: buildah-helper
      configMap:
        defaultMode: 0700
        name: {{.SpecialResource.Name}}-buildah-helper
