apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
 name: {{ printf "%s-%s" .Values.specialResourceModule.metadata.name .Values.openShiftVersion | replace "." "-" | replace "_" "-" | trunc 63 }}
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - local-cluster
    - key: openshiftVersion
      operator: In
      values:
      - {{ .Values.openShiftVersion }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
 name: {{ printf "%s-%s" .Values.specialResourceModule.metadata.name .Values.openShiftVersion | replace "." "-" | replace "_" "-" | trunc 63 }}
placementRef:
 apiGroup: apps.open-cluster-management.io
 kind: PlacementRule
 name: {{ printf "%s-%s" .Values.specialResourceModule.metadata.name .Values.openShiftVersion | replace "." "-" | replace "_" "-" | trunc 63 }}
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: {{ printf "%s-%s" .Values.specialResourceModule.metadata.name .Values.openShiftVersion | replace "." "-" | replace "_" "-" | trunc 63 }}
