apiVersion: sro.openshift.io/v1beta1
kind: SpecialResourceModule
metadata:
  name: acm-ice
spec:
  namespace: acm-ice
  chart:
    name: acm-ice
    version: 0.0.1
    repository:
      name: acm-ice
      url: cm://acm-ice/acm-ice-chart
  set:
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    buildArgs:
      - name: DRIVER_VER
        value: "1.6.4"
    registry: quay.io/openshift
  watch:
    - path: $.status.clusterClaims[?(@.name == 'osimage.openshift.io')].value
      apiVersion: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
