---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverBuild}}-4.7.18
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverBuild}}-4.7.18
  annotations:
    specialresource.openshift.io/wait: "true"
    specialresource.openshift.io/kernel-affine: "true"
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  source:
    git:
      ref: {{.Values.specialresource.spec.driverContainer.source.git.ref}}
      uri: {{.Values.specialresource.spec.driverContainer.source.git.uri}}
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.SRO
      buildArgs:
        - name: "IMAGE"
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:9bdb4bea84b9681d48349f544e3053c5a14057d5ce56cce939d00d7b3422ac71
        {{- range $arg := .Values.buildArgs }}
        - name: {{ $arg.name }}
          value: {{ $arg.value }}
        {{- end }}
        - name: KVER
          value: "4.18.0-240.22.1.el8_3.x86_64"
  output:
    to:
      kind: "DockerImage"
      name: {{ .Values.imageToSign }}
    pushSecret:
      name: {{ .Values.pushSecret }}


