apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-script
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
data:
  webhook.yaml: |
    {{- include "webhooks.yaml.tpl" . | indent 4}}
