apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-hook-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install, pre-delete, pre-upgrade, post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded, hook-failed
