apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: special-resource-operator-tls
  labels:
    control-plane: controller-manager
  name: special-resource-controller-manager-metrics-service
  namespace: openshift-special-resource-operator
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
