apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  labels:
    control-plane: controller-manager
  name: special-resource-controller-manager-metrics-monitor
  namespace: openshift-special-resource-operator
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: special-resource-operator-controller-manager-metrics-service.openshift-sro.svc
  namespaceSelector:
    matchNames:
    - openshift-sro
  selector:
    matchLabels:
      control-plane: controller-manager
