# permissions for end users to edit specialresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: specialresource-editor-role
rules:
- apiGroups:
  - sro.openshift.io
  resources:
  - specialresources
  - specialresourcemodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sro.openshift.io
  resources:
  - specialresources/status
  - specialresourcemodules/status
  verbs:
  - get
