// Code generated by MockGen. DO NOT EDIT.
// Source: resource.go

// Package resource is a generated GoMock package.
package resource

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// MockResourceAPI is a mock of ResourceAPI interface.
type MockResourceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockResourceAPIMockRecorder
}

// MockResourceAPIMockRecorder is the mock recorder for MockResourceAPI.
type MockResourceAPIMockRecorder struct {
	mock *MockResourceAPI
}

// NewMockResourceAPI creates a new mock instance.
func NewMockResourceAPI(ctrl *gomock.Controller) *MockResourceAPI {
	mock := &MockResourceAPI{ctrl: ctrl}
	mock.recorder = &MockResourceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceAPI) EXPECT() *MockResourceAPIMockRecorder {
	return m.recorder
}

// CreateFromYAML mocks base method.
func (m *MockResourceAPI) CreateFromYAML(arg0 context.Context, arg1 []byte, arg2 bool, arg3 v1.Object, arg4, arg5 string, arg6 map[string]string, arg7, arg8 string, arg9 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromYAML", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFromYAML indicates an expected call of CreateFromYAML.
func (mr *MockResourceAPIMockRecorder) CreateFromYAML(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromYAML", reflect.TypeOf((*MockResourceAPI)(nil).CreateFromYAML), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
}

// GetObjectsFromYAML mocks base method.
func (m *MockResourceAPI) GetObjectsFromYAML(arg0 []byte) (*unstructured.UnstructuredList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectsFromYAML", arg0)
	ret0, _ := ret[0].(*unstructured.UnstructuredList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectsFromYAML indicates an expected call of GetObjectsFromYAML.
func (mr *MockResourceAPIMockRecorder) GetObjectsFromYAML(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectsFromYAML", reflect.TypeOf((*MockResourceAPI)(nil).GetObjectsFromYAML), arg0)
}
