apiVersion: v1
entries:
  fpga-xrt-driver:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-07T18:24:34.213106621+02:00"
    description: A Helm chart for Kubernetes
    digest: cee9af3dc68ad17e51086259cdca09ced8aec960af4c52aef6c1c90648ff3cfe
    name: fpga-xrt-driver
    type: application
    urls:
    - file:///charts/xilinx/fpga-xrt-driver-4.7.11.tgz
    version: 4.7.11
generated: "2021-10-07T18:24:34.212765029+02:00"
