apiVersion: v1
entries:
  fpga-xrt-driver:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-04T08:14:28.457018157+01:00"
    description: A Helm chart for Kubernetes
    digest: 932eb7385f7516919e5110fd8699f01ddb1fef0ab2ace97e963ef0b5c9cac1bb
    name: fpga-xrt-driver
    type: application
    urls:
    - file:///charts/xilinx/fpga-xrt-driver-4.7.11.tgz
    version: 4.7.11
generated: "2021-11-04T08:14:28.456287563+01:00"
