apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverContainer}}-{{.Values.operatingSystemMajor}}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.specialresource.metadata.name}}-rest-cert
  annotations:
     specialresource.openshift.io/wait: "true"
spec:
  serviceAccount: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverContainer}}-{{.Values.operatingSystemMajor}}
  dnsNames:
    - {{.Values.specialresource.metadata.name}}-rest.{{.Values.specialresource.spec.namespace}}.svc.cluster.local
    - {{.Values.specialresource.metadata.name}}-rest.{{.Values.specialresource.spec.namespace}}.svc
    - {{.Values.specialresource.metadata.name}}-rest.{{.Values.specialresource.spec.namespace}}
    - {{.Values.specialresource.metadata.name}}-rest

  secretName: rest-tls-cert
  duration: 8760h # 365d
  renewBefore: 720h # 30d
  issuerRef:
    name: infoscale-cert-issuer
