apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: {{.Values.specialresource.metadata.name}}-csi-cert
 annotations:
     specialresource.openshift.io/wait: "true"
spec:
 commonName: csi-plugin
 secretName: csi-tls-cert
 duration: 8760h # 365d
 renewBefore: 720h # 30d
 issuerRef:
   name: infoscale-cert-issuer
