apiVersion: v1
entries:
  ping-pong:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-30T12:41:48.588977365-04:00"
    description: Simple go app to showcase cert-manager intergration
    digest: 9944caf95c6e881f07fb3709e0006c1e9e9347d9c35cf10c28f0edf74dcb30ba
    icon: https://avatars.githubusercontent.com/u/55542927
    name: ping-pong
    type: application
    urls:
    - file:///charts/example/ping-pong-0.0.1.tgz
    version: 0.0.1
  simple-kmod:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2021-06-30T12:41:48.589158231-04:00"
    description: Simple kmod will deploy a simple kmod driver-container
    digest: 26dc92d07de35113d0e00da1b33b5f9c0f6e5d6ee6296159de44a02d310964a6
    icon: https://avatars.githubusercontent.com/u/55542927
    name: simple-kmod
    type: application
    urls:
    - file:///charts/example/simple-kmod-0.0.1.tgz
    version: 0.0.1
generated: "2021-06-30T12:41:48.588643497-04:00"
