apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pull_secret_creds | quote }}
kind: Secret
metadata:
  name: {{.Values.specialresource.metadata.name}}-{{.Values.groupName.driverContainer}}
type: kubernetes.io/dockerconfigjson

