// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go

// Package metrics is a generated GoMock package.
package metrics

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// SetCompletedKind mocks base method.
func (m *MockMetrics) SetCompletedKind(specialResource, kind, name, namespace string, value int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCompletedKind", specialResource, kind, name, namespace, value)
}

// SetCompletedKind indicates an expected call of SetCompletedKind.
func (mr *MockMetricsMockRecorder) SetCompletedKind(specialResource, kind, name, namespace, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompletedKind", reflect.TypeOf((*MockMetrics)(nil).SetCompletedKind), specialResource, kind, name, namespace, value)
}

// SetCompletedState mocks base method.
func (m *MockMetrics) SetCompletedState(specialResource, state string, value int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCompletedState", specialResource, state, value)
}

// SetCompletedState indicates an expected call of SetCompletedState.
func (mr *MockMetricsMockRecorder) SetCompletedState(specialResource, state, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompletedState", reflect.TypeOf((*MockMetrics)(nil).SetCompletedState), specialResource, state, value)
}

// SetSpecialResourcesCreated mocks base method.
func (m *MockMetrics) SetSpecialResourcesCreated(value int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSpecialResourcesCreated", value)
}

// SetSpecialResourcesCreated indicates an expected call of SetSpecialResourcesCreated.
func (mr *MockMetricsMockRecorder) SetSpecialResourcesCreated(value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSpecialResourcesCreated", reflect.TypeOf((*MockMetrics)(nil).SetSpecialResourcesCreated), value)
}
