apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: special-resource-controller-manager
  namespace: openshift-special-resource-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELEASE_VERSION
          value: 0.0.1-snapshot
        - name: SSL_CERT_DIR
          value: /etc/pki/tls/certs
        image: quay.io/openshift-psap/special-resource-operator:sign-image
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      securityContext:
        runAsGroup: 499
        runAsNonRoot: true
        runAsUser: 499
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: cache-volume
