apiVersion: v1
entries:
  shipwright:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2021-07-29T12:32:24.596630638-04:00"
    description: Build v2
    digest: 35732ef53485db45a215b7031a7b698bac7f190a9dc7f5a3da9d5ec463da8e47
    icon: https://avatars.githubusercontent.com/u/55542927
    name: shipwright
    type: application
    urls:
    - file:///charts/staging/shipwright-4.7.0.tgz
    version: 4.7.0
generated: "2021-07-29T12:32:24.595869682-04:00"
