apiVersion: v1
entries:
  shipwright:
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2021-11-04T08:14:28.3752992+01:00"
    description: Build v2
    digest: fc79321078b8b6aead0490ff90c78fe2d77f2346174da852ee501430a8561eeb
    icon: https://avatars.githubusercontent.com/u/55542927
    name: shipwright
    type: application
    urls:
    - file:///charts/staging/shipwright-4.7.0.tgz
    version: 4.7.0
generated: "2021-11-04T08:14:28.373865228+01:00"
