{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-license
  namespace: {{ .Release.Namespace }} #kube-system
stringData:
  LICENSE: {{ .Values.license }}
type: Opaque
{{- end }}
