apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: centos-simple-kmod
spec:
  namespace: centos-simple-kmod
  nodeSelector: 
    node-role.kubernetes.io/node: ""
  chart:
    name: centos-simple-kmod
    version: 0.0.1
    repository:
      name: example
      url: file:///charts/example
  set:
    pull_secret_creds: "ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJaR0ZuY21GNUsyTmxiblJ2YzE5emFXMXdiR1ZmYTIxdlpEcEVSbFU1T0ZSUlZqTXlVVGhhVWpaU1ZGSk1OVGRNV0ZveU1ERkxValJSVlZwUldrSlBTMHBST0U1VlZqSlpOVnBaUmxRd1FsQTFUakkyUVV0WVZGVTUiLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==" # pull secret .dockerconfigjson value. Should be a robot account
    image_repo: "quay.io/dagray/centos8-simple-kmod"
    kind: Values
    apiVersion: sro.openshift.io/v1beta1
    kmodNames: ["simple-kmod", "simple-procfs-kmod"]
    buildArgs:
    - name: "KMODVER"
      value: "SRO"
  driverContainer:
    source:
      git:
        ref: "vanilla-k8s-centos"
        uri: "https://github.com/dagrayvid/kvc-simple-kmod.git"
