apiVersion: v1
entries:
  infoscale-vtas:
  - apiVersion: v2
    appVersion: 8.0.0.0000
    created: "2021-10-27T03:24:39.01424811-05:00"
    description: A Helm chart for the deployment of Veritas InfoScale Resources
    digest: f40cbdcaea27524963806ddc2f7ebeb3ee595d6b4985358c49099e4fffe663f6
    name: infoscale-vtas
    type: application
    urls:
    - file:///charts/infoscale/infoscale-vtas-0.0.1.tgz
    version: 0.0.1
generated: "2021-10-27T03:24:39.013694233-05:00"
